name: Hello Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello ${{ github.repository_owner }}!"
